title: Documentation UniWIP CDR 2025
description: Documentation de l'équipe UniWIP pour la CDR 2025
theme: just-the-docs

url: https://unimakers.github.io/uniwip-cdr2025-docs

aux_links:
  Les Dépots de la team UniWIP: https://github.com/orgs/Unimakers/teams/uniwip/repositories
